const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
const ADD_TODO_FAILURE = "ADD_TODO_FAILURE";
const ADD_TODO_STARTED = "ADD_TODO_STARTED";

export { ADD_TODO_SUCCESS, ADD_TODO_FAILURE, ADD_TODO_STARTED };
